services:
  # Backend service (Express API)
  - type: web
    name: vibecall-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend service (Vite + React)
  - type: web
    name: vibecall-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://vibecall-backend.onrender.com
